# Generated by Django 4.0.4 on 2022-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientName',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('guardian', models.CharField(max_length=30, null=True)),
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
