# Generated by Django 4.0.4 on 2022-05-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('guardian', models.CharField(max_length=30, null=True)),
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('plot', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('size', models.IntegerField(null=True)),
                ('block', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('agent', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('client', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.client')),
                ('property', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.property')),
            ],
        ),
    ]
