# Generated by Django 4.0.4 on 2022-06-13 13:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('guardian', models.CharField(max_length=30, null=True)),
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('guardian', models.CharField(max_length=30, null=True)),
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('plot', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('block', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('payment', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=3), size=None)),
                ('agent', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.agent')),
                ('client', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.client')),
                ('property', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.property')),
            ],
        ),
    ]
