# Generated by Django 4.0.4 on 2022-05-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientName',
            new_name='Client',
        ),
    ]
