# Generated by Django 4.0.4 on 2022-05-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_rename_clientname_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cnic',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
