# Generated by Django 4.0.2 on 2022-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('plot', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('size', models.IntegerField(null=True)),
                ('block', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=12)),
            ],
        ),
    ]
