# Generated by Django 4.0.2 on 2022-05-13 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_property_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('agent', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=5)),
                ('client', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.client')),
                ('property', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.property')),
            ],
        ),
    ]
