# Generated by Django 4.0.2 on 2022-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='agent',
            field=models.CharField(default='Agent01', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
