# Generated by Django 4.0.4 on 2022-05-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_file_agent_alter_file_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
