# Generated by Django 4.0.4 on 2022-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=60)),
                ('guardian', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('cnic', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
